// Copyright 2025 Artiom Khachaturian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once // ChatMessage.h
#include <string>
#include <optional>
#include <vector>

namespace LiveKitCpp
{

struct ChatMessage
{
    std::string _id; // uuid
    int64_t _timestamp = {};
    // populated only if the intent is to edit/update an existing message
    std::optional<int64_t> _editTimestamp;
    std::string _message;
    bool _deleted = {}; // true to remove message
    // true if the chat message has been generated by an agent from a participant's audio transcription
    bool _generated = {};
};
	
}
