// Copyright 2025 Artiom Khachaturian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once // DataStreamTextHeader.h
#include "livekit/signaling/sfu/DataStreamTextHeaderOperationType.h"
#include <string>
#include <vector>

namespace LiveKitCpp
{

struct DataStreamTextHeader
{
    DataStreamTextHeaderOperationType _operationType = {};
    // Optional: Version for updates/edits
    int32_t _version = {};
    // Optional: Reply to specific message
    std::string _replyToStreamId;
    // file attachments for text streams
    std::vector<std::string> _attachedStreamIds;
    // true if the text has been generated by an agent from a participant's audio transcription
    bool _generated = {};
};
	
} // namespace LiveKitCpp
