// Copyright 2025 Artiom Khachaturian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once // SessionListener.h
#include "LiveKitError.h"
#include "ParticipantListener.h"
#include "SessionState.h"
#include <string>

namespace LiveKitCpp
{

class SessionListener : public ParticipantListener
{
public:
    virtual void onStateChanged(SessionState /*state*/) {}
    virtual void onError(LiveKitError /*error*/, const std::string& /*what*/ = {}) {}
    virtual void onLocalParticipantJoined() {}
    virtual void onLocalParticipantLeaved() {}
    virtual void onRemoteParticipantAdded(const std::string& /*remoteParticipantSid*/) {}
    virtual void onRemoteParticipantRemoved(const std::string& /*remoteParticipantSid*/) {}
    virtual void onUserPacketReceived(const std::string& /*remoteParticipantSid*/,
                                      const std::string& /*remoteParticipantIdentity*/,
                                      const std::string& /*payload*/,
                                      const std::string& /*topic*/) {}
    virtual void onChatMessageReceived(const std::string& /*remoteParticipantIdentity*/,
                                       const std::string& /*message*/, // uuid
                                       const std::string& /*id*/,
                                       // time in milliseconds since the epoch (January 1, 1970, UTC)
                                       int64_t /*timestamp*/,
                                       bool /*deleted*/, // true to remove message
                                       // true if the chat message has been generated by
                                       // an agent from a participant's audio transcription
                                       bool /*generated*/) {}
protected:
    virtual ~SessionListener() = default;
};

} // namespace LiveKitCpp
