// Copyright 2025 Artiom Khachaturian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once // DataChannelsStorage.h
#include "DataChannel.h"
#include "Loggable.h"
#include "Listener.h"
#include "SafeObj.h"
#include "livekit/signaling/SignalServerListener.h"
#include <memory>
#include <optional>
#include <unordered_map>
#include <api/scoped_refptr.h>

namespace LiveKitCpp
{

class DataExchangeListener;

class DataChannelsStorage : private Bricks::LoggableS<SignalServerListener>
{
    class Wrapper;
    // key is channel label
    using DataChannels = std::unordered_map<std::string, std::shared_ptr<Wrapper>>;
public:
    DataChannelsStorage(const std::shared_ptr<Bricks::Logger>& logger = {},
                        std::string logCategory = "data_channels");
    ~DataChannelsStorage() override;
    void setSid(const std::string& sid) { _sid(sid); }
    void setIdentity(const std::string& identity) { _identity(identity); }
    void setListener(DataExchangeListener* listener = nullptr);
    bool add(rtc::scoped_refptr<DataChannel> channel);
    bool remove(const std::string& label);
    bool remove(const rtc::scoped_refptr<DataChannel>& channel);
    void clear();
    bool sendUserPacket(std::string payload, bool reliable,
                        const std::string& topic = {},
                        const std::vector<std::string>& destinationSids = {},
                        const std::vector<std::string>& destinationIdentities = {}) const;
    // generated is true if the chat message has been generated by an agent
    // from a participant's audio transcription
    bool sendChatMessage(std::string message, bool deleted, bool generated = false,
                         const std::vector<std::string>& destinationIdentities = {}) const;
private:
    std::shared_ptr<Wrapper> getChannelForSend(bool reliable) const;
    // overrides of Bricks::LoggableS<>
    std::string_view logCategory() const final { return _logCategory; }
    // overrides OF SignalServerListener
    void onDataPacket(const DataPacket& packet) final;
    void onSignalParseError(const std::string& details) final;
private:
    const std::string _logCategory;
    Bricks::SafeObj<DataChannels> _dataChannels;
    Bricks::Listener<DataExchangeListener*> _listener;
    // from owner
    Bricks::SafeObj<std::string> _identity;
    Bricks::SafeObj<std::string> _sid;
};

} // namespace LiveKitCpp
